repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: dist/
      - id: end-of-file-fixer
        exclude: dist/
      - id: check-json
        exclude: \.devcontainer/
      - id: check-yaml
      - id: check-merge-conflict
