blank_issues_enabled: false
contact_links:
  - name: Ask a question/open a discussion
    url: https://github.com/foXaCe/dreame-vacuum-card/discussions
    about: To ask a question or open a discussion please use a dedicated section.
